project
northmule/gofermart pull request #4
Opened 2024-09-16 10:51 UTC by northmule

2024-09-17 03:33 UTC, vokinneberg requested changes
Фух 😓, время летит быстро, и мы уже подобрались к первому выпускному проекту! 🎉 По традиции поздравляю с первым ревью, желаю удачи 🍀 и получить удовольствие от реализации проекта 💪 Хочу отметить сильные стороны твоего PR, а также сделать несколько комментариев по поводу того, на что стоит обратить внимание и что можно улучшить. 🤓

**Сильные стороны твоего PR:**

- Твой код имеет достаточно чёткую структуру! 💪
- Реализация достаточно простая, не перегружена деталями и позволяет легко разобраться в логике 👍
- Ты покрыл часть компонентов Unit-тестами.
- Реализованный функционал проходит автотесты! ⚡

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Файлы `.idea` не обязательно коммитить в репозиторий и можно добавить в `.gitignore`.
- В момент инициализации приложения, насколько я понимаю, `&lt;-ctx.Done()` пришлёт значение в канал в момент, когда будет обработан один из сигналов. Получается, что если этого не произойдёт, но `err = httpServer.ListenAndServe()` выполнится с ошибкой и горутина завершится, мы так и останемся ожидать сигнала, при этом сервер не будет работать? Кажется, стоит разобраться с этим моментом.
- Почему бы нам везде не использовать либо глобальный логгер `logger.LogSugar`, либо инстанс `loggerService`? Использование их вместе выглядит избыточно.
- Контекст не стоит хранить в структуре, упоминание об этом есть в документации к пакету https://pkg.go.dev/context. Дело в том, что контекст создаётся, как правило, per-request, если контекст живёт на протяжении всего цикла жизни структуры, это может приводить к неявным ошибкам. Стоит передавать контекст как параметр в метод, который вызывается.
- В нотации Go сообщения об ошибках должны начинаться с буквы в нижнем регистре (за исключением аббревиатур), так как если будет использоваться цепочка ошибок, буква в верхнем регистре не появится в середине сообщения.
- Не стоит возвращать ссылку на интерфейс, так как в этом нет необходимости. Так как Go использует duck typing, реализация будет автоматически реализовывать интерфейс. Вообще стоит подумать о том, чтобы определить интерфейс там, где он используется (в сервисе или хендлере).
- В случае слайса нет смысла использовать указатель, так как слайс передаётся по указателю.
- В общем случае стоит "омитить" те поля, которые не имеют значения, когда они не установлены. Мне кажется, такое поле как `CreatedAt` должно быть установлено всегда?
- Я бы рекомендовал разделять фабричный метод, назначение которого инициализировать структуру, и запуск методов структуры. Советую запускать их явно — например, создать метод `Run(...)`, в который можно передать контекст. Это будет гораздо нагляднее. "Неявный" запуск чего бы то ни было в фабричном методе может запутать.
- В воркере происходит множество связанных операций, которые меняют данные в БД. Стоит их выполнять в transaction scope, так как в противном случае есть риск получить неконсистентное состояние в БД.

2024-09-17 03:33 UTC, vokinneberg commented on README.md
> +# Накопительная система лояльности «Гофермарт»
В README так же можно добавить информацию и том как собирать, запускать и  тестировать сервис. Так же можно добавить информацию о конфигурации.

2024-09-17 03:33 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	loggerService, err := logger.NewLogger("info")
Стоит брать уровень логирования так же из настроек сервиса, так как в разных окружениях может потребоваться разный уровень логирования.

2024-09-17 03:33 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	defer cancel()
Второй `defer`  кажется лишним, если один уже есть?

2024-09-17 03:33 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	<-ctx.Done()
Насколько я понимаю, `<-ctx.Done()`  пришлет значение в канал в момент, когда будет обработан один из сигналов. Получается, что если этого не произойдет, но `err = httpServer.ListenAndServe()` выполнится с ошибкой и горутина завершится мы так и останемся ожидать сигнала при этом сервер не будет работать? Кажется стоит разобраться с этим моментом.

2024-09-17 03:33 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	loggerService, err := logger.NewLogger("info")
Почему бы нам везде не использовать либо глобальный логгер `logger.LogSugar`, либо инстанс `loggerService`? Использование их вместе выглядит избыточно.

2024-09-17 03:33 UTC, vokinneberg commented on config/config.go
> +	return instance, instance.flag()
Элегантно, но не совсем хорошо читается. То, что `instance` обновит значения при вызове `instance.flag()` не совсем очевидно. Я бы сделал проще:
```suggestion
         if err := instance.flag(); err != nil {
                 return nil, err
          }
	return instance, nil
```

2024-09-17 03:33 UTC, vokinneberg commented on config/config.go
> +		return err
Не обязательно логировать прямо в момент возникновения ошибки. Бывает удобнее просто обернуть ошибку, прокинуть вверх по стеку и залогировать там. 
```suggestion
		return fmt.Errorf("флаги конфигурации не разобраны: %w", err)
```

2024-09-17 03:33 UTC, vokinneberg commented on config/config_test.go
> +	// Проверяем значения конфигурации
Во всех трех тестах проверки очень похожи. Возможно стоит использовать табличные тесты?

2024-09-17 03:33 UTC, vokinneberg commented on db/migrations.go
> +	ctx   context.Context
Контекст не стоит хранить контекст в структуре, упоминание об этом есть даже в документации к пакету https://pkg.go.dev/context. Дело в том, что контекст создается как правило per-request, если контекст живет на протяжении всего цикла жизни структуры этом может приводить к неявным ошибкам. Стоит передавать контекст, как параметр в метод, который вызывается.

2024-09-17 03:33 UTC, vokinneberg commented on db/migrations.go
> +func NewMigrations(db *sql.DB, ctx context.Context) *Migrations {
Если конекст передается, как параметр стоит сделать его первым параметром.
```suggestion
func NewMigrations(ctx context.Context, db *sql.DB) *Migrations {
```

2024-09-17 03:33 UTC, vokinneberg commented on db/migrations.go
> +	if err := goose.UpContext(m.ctx, m.sqlDB, "migrations"); err != nil {
Здесь стоит использовать контекст из параметра, а не из самой структуры.

2024-09-17 03:33 UTC, vokinneberg commented on db/migrations/20240906090408_withdrawn_table.sql
> +CREATE TABLE public.withdrawn (
Существительное в множественном числе будет более консистентно с наименованиями остальных  колонок.

```suggestion
CREATE TABLE public.withdrawals (
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/accrual/api/client/client.go
> +	return fmt.Sprintf("Сервис %s вернул пустой ответ", ServiceName)
В нотации  Go сообщения об ошибках должны начинаться с буквы в нижнем регистре (за исключением аббревиатур), так как если будет использоваться цепочка ошибок буква в верхнем регистре не появится в середине сообщения.
```suggestion
	return fmt.Sprintf("cервис %s вернул пустой ответ", ServiceName)
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/accrual/api/client/client.go
> +	ctx        context.Context
Выше написал про использование контекста.

2024-09-17 03:33 UTC, vokinneberg commented on internal/accrual/api/client/client.go
> +	isStatusOk(response *http.Response) (bool, error)
Не совсем понимаю для чего нужен неэкспортируемый метод в интерфейсе?

2024-09-17 03:33 UTC, vokinneberg commented on internal/accrual/api/client/client.go
> +func NewAccrualClient(serviceURL string, logger *zap.SugaredLogger, ctx context.Context) AccrualClientInterface {
Не стоит возвращать ссылку на интерфейс так как в этом нет необходимости. Так как Go использует  duck typing, реализация будет автоматически реализовывать интерфейс. Вообще стоит подумать о том чтобы определить интерфейс там где он используется (в сервисе или хэндлере). 

```suggestion
func NewAccrualClient(serviceURL string, logger *zap.SugaredLogger, ctx context.Context) *AccrualClient {
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/routes.go
> +			contextMiddleware,
Мне кажется, как минимум `contextMiddleware` можно вынести на уровень  выше так чтобы не нужно было его передавать каждый раз.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/registration.go
> +			UUID:     uuid.NewString(),
А для чего нам `UUID` если у нас есть `id`  пользователя в БД? И если мы хотим по какой-то причине использовать UUID возможно стоит его использовать как PRIMARY KEY?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/registration.go
> +			Name:     "Имя",
Это не ошибка? `name` будет всегда `Имя`?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/routes.go
> +		r.With(
А почему в этом случае было выбрано все хэндлеры реализовать в виде middleware?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/balance.go
> +		logger.LogSugar.Error(err.Error())
Стоит добавить контекста к сообщению об ошибке. zap.Error(err) - добавить в лог поле `error`.
```suggestion
		logger.LogSugar.Error("маршаллинг ответа", zap.Error(err))
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/accrual.go
> +		logger.LogSugar.Infof("Создаю информацию о нулевом списании по заказу %s", newOrder.Number)
Можно сделать сообщение более структурированным при помощи вспомогательных методов `zap`.

```suggestion
		logger.LogSugar.Infof("Создаю информацию о нулевом списании по заказу %s",  zap.Int("number", newOrder.Number))
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/job.go
> +func (jh *JobHandler) CreateTaskToProcessNewOrder(next http.Handler) http.Handler {
Хэндлер называется `JobHandler`, а метод называется `CrateTask...`. Мне кажется чтоит назвать их консистентно?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/order.go
> +		if !o.orderService.ValidateOrderNumber(orderNumber) {
Более канонический стиль проверки в Go.
```suggestion
		if valid := o.orderService.ValidateOrderNumber(orderNumber); !valid {
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/order.go
> +	instance.sqlFindOrdersByUserUUID, err = store.Prepare(`select
  Стоит отформатировать SQL строку, в противном случае ее очень сложно прочитать.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/order.go
> +func (o *OrderRepository) FindOrdersByUserUUID(userUUID string) (*[]models.Order, error) {
 В случае слайса нет смысла использовать указатель, так как слайс передается по указателю.
```suggestion
func (o *OrderRepository) FindOrdersByUserUUID(userUUID string) ([]models.Order, error) {
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/order.go
> +	return &orders, nil
```suggestion
	return orders, nil
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/api/handlers/withdraw.go
> +	order, err := wh.manager.Order().FindByNumberOrCreate(request.Order, user.ID) // создание заказа если он не найден (ошибка теста или ТЗ ? )
А что ожидает тест?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/models/accrual.go
> +	ID        int       `json:"id,omitempty"`
 Эта директива уберет `ID` из JSON если равен 0. Это действительно то, чего мы хотим?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/models/user.go
> +	CreatedAt time.Time `json:"created_at,omitempty"`
В общем случае стоит "омитить" те поля, который не имеют значения когда они не установлены. Мне кажется такое поле как `CratedAt` должно быть установлено всегда?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/models/withdrawn.go
> +	CreatedAt sql.NullTime `json:"created_at"`
`CreatedAt` разве может быть `Null`?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/models/order.go
> +	CreatedAt sql.NullTime    `json:"created_at,omitempty"`
`CreatedAt` разве может быть `Null`?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/models/job.go
> +	CreatedAt   sql.NullTime `json:"created_at,omitempty"`
`CreatedAt` разве может быть `Null`?

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/models/order.go
> +	User      User            `json:"user"`
Я бы рекомендовал для других сущностей использовать указатель.
```suggestion
	User      *User            `json:"user"`
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/order_test.go
> +func TestOrderRepositoryTestSuite(t *testing.T) {
Было бы здорово добавить больше кейсов.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/repository/withdrawn.go
> +func (wr *WithdrawnRepository) FindWithdrawsByUserUUID(userUUID string) (*[]models.Withdrawn, error) {
```suggestion
func (wr *WithdrawnRepository) FindWithdrawsByUserUUID(userUUID string) ([]models.Withdrawn, error) {
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/services/authentication/authentication.go
> +func ValidateToken(userUUID string, token string, secretKey string) bool {
Token так же можно проверять на истечение срока действия.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/storage/session_storage.go
> +	sessionUserUUID, ok := s.Values[key]
Тут так же стоит использовать `lock` на чтение.

```suggestion
        s.mx.RLock()
	defer s.mx.RUnlock()
	sessionUserUUID, ok := s.Values[key]
```

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/worker/worker.go
> +	for i := 1; i <= workerNum; i++ {
Вообще я бы рекомендовал разделять фабричный метод, назначение которого инициализировать структуру и запуск методов структуры. Советую запускать их явно - например создать метод `Run(...)`  в который можно передать контекст. Это будет гораздо нагляднее. "Неявный" запуск чего бы то ни было в фабричном методе может запутать.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/worker/worker.go
> +func (w *Worker) worker(num int, jobCh <-chan job) {
В воркере происходит множество связанных операций, которые меняют данные в БД. Стоит из выполнять в transaction scope так как в противном случае есть риск получить неконсистентное состояние в БД.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/worker/worker.go
> +			if errors.As(err, &errorUndefined) {
Этот блок практически идентичен первому и третьему. Думаю их стоит объединить.

2024-09-17 03:33 UTC, vokinneberg commented on internal/app/worker/worker.go
> +			response, err := w.accrualService.SendOrderNumber(item.jobRun.OrderNumber)
Было бы здорово добавить комментарии с описанием того, что проверяют эти блоки и как они работают.

2024-09-19 17:42 UTC, northmule commented on internal/app/api/routes.go
> +			contextMiddleware,
Здесь возникает ошибка с chi в месте /pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:426 
```
// Grab the route context object
	rctx := r.Context().Value(RouteCtxKey).(*Context)
```
```
 panic: interface conversion: interface {} is nil, not *chi.Context
 
 -> github.com/go-chi/chi/v5.(*Mux).routeHTTP
 ->   /home/djo/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/mux.go:428

    net/http.HandlerFunc.ServeHTTP
      /home/djo/go/go1.22.7/src/net/http/server.go:2171
    github.com/go-chi/chi/v5/middleware.(*Compressor).Handler-fm.(*Compressor).Handler.func1
      /home/djo/go/pkg/mod/github.com/go-chi/chi/v5@v5.1.0/middleware/compress.go:209

```
По этому пока оставил этот хэндлер в каждом роуте

2024-09-19 17:45 UTC, northmule commented on internal/app/api/handlers/registration.go
> +			UUID:     uuid.NewString(),
UUID потенциально можно использовать в сторонних сервисах как универсальный идентификатор объекта

2024-09-19 18:12 UTC, northmule commented on internal/app/api/routes.go
> +		r.With(
С перспективой на рефакторинг, что бы можно было разделить middleware на более узкие в рамках одного запроса

2024-09-20 15:46 UTC, northmule commented on internal/app/api/handlers/withdraw.go
> +	order, err := wh.manager.Order().FindByNumberOrCreate(request.Order, user.ID) // создание заказа если он не найден (ошибка теста или ТЗ ? )
Если судить по ТЗ. То здесь нет упоминания о том что заказ предварительно должен быть создан в системе и судя по автотестам, там оно и есть. Для того что бы вписать это поведение в приложение - добавил метод FindByNumberOrCreate

2024-10-02 02:52 UTC, vokinneberg approved these changes
Второе ревью! 🎉 Ты реализовал большое количество предложений, которые я сделал на предыдущем ревью, здорово! 👍 В общем, твоё приложение функционально и проходит все функциональные тесты. 🚀 Тем не менее, я всё ещё вижу несколько фундаментальных проблем, которые мне бы хотелось исправить вместе с тобой. 

**Сильные стороны твоего PR:**

- Спасибо за то, что добавил полезную информацию в README. 🙏
- Здорово, что ты добавил unit-тесты в приложение! ⚡
- Ты выполняешь запросы к БД в transaction scope. 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- Нет необходимости коммитить бинарники типа `goose` в репозиторий.
- Нам точно нужен пустой файл [[TODO.md](http://todo.md/)](http://TODO.md)?
- Всё ещё не совсем понимаю механизм graceful shutdown и в какой момент приложение отменит контекст, и в целом, как будет обработано завершение приложения?
- Вообще хранение и совершение операций с деньгами при помощи типов с плавающей точкой могут вести к неявным ошибкам, так как при математических операциях могут быть неявные округления и т.д., поскольку это бинарные, а не десятичные типы. Я бы рекомендовал использовать либо то, что называется minimal currency unit (т.е. хранить копейки вместо рублей в целочисленном типе и форматировать их соответствующим образом, когда это необходимо), либо использовать тип `decimal`. Так как в Go нет нативного `decimal` типа, можно использовать сторонние библиотеки.
- Если честно, подход с реализацией бизнес-логики в middleware мне кажется избыточным. По моему мнению, в общем случае middleware стоит использовать для реализации общих технических аспектов, которые напрямую не относятся к бизнес-логике приложения: логирование, сжатие, авторизация, recovery и т.д. То, что, как правило, будет использоваться несколько раз для разных маршрутов приложения. Бизнес-логику всё же стоит поместить на уровень хэндлера или сервиса, если такой слой есть в приложении, и не стоит разделять на отдельные файлы, так как это только добавляет дополнительную когнитивную нагрузку и усложняет понимание того, как же работает приложение, не говоря уже о тестировании.
- Стоит добавить индексы на поля, по которым происходит поиск в БД.
- Ты добавил значительное количество unit-тестов, и это здорово, но нет, на мой взгляд, самого главного — тестов хэндлеров, которые бы проверяли, что хэндлеры возвращают корректный код ответа и данные. Было бы здорово реализовать такие тесты.
- Ты логируешь во всех слоях приложения, на самом деле, на мой взгляд, такое логирование немного избыточно и создаёт много «шума». В Go существует техника враппинга ошибок, когда к ошибке добавляется контекст, и она возвращается вверх по стеку вызовов, где логируется в некой единой точке обработки. Рекомендую попробовать использовать такую технику.

2024-10-02 02:52 UTC, vokinneberg commented on README.md
> +Получение информации о расчёте начислений
👍 Спасибо за то, что добавил полезную информацию в README!

2024-10-02 02:52 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	_, err = logger.NewLogger(cfg.LogLevel)
👍

2024-10-02 02:52 UTC, vokinneberg commented on cmd/gophermart/main.go
> +	logger.LogSugar.Infof("Конфигурация приложения %#v", cfg)
Мне кажется тут получилась немного "простыня". Было бы здорово разделить хотя бы пустыми строками этапы инициализации прилдожения.

2024-10-02 02:52 UTC, vokinneberg commented on cmd/gophermart/main.go
> +		<-ctx.Done()
Все еще не совсем понимаю механизм graceful shutdown и в какой момент приложение отменит контекст?

2024-10-02 02:52 UTC, vokinneberg commented on config/config_test.go
> +			assert.Equal(t, test.expected.LogLevel, cfg.LogLevel)
По-моему можно сделать просто вот так,. сравнивая структуры целиком, а не отдельные поля:
```suggestion
			assert.Equal(t, test.expected, cfg)
```

2024-10-02 02:52 UTC, vokinneberg commented on db/migrations.go
> +func (m *Migrations) Up(ctx context.Context) error {
👍 за передачу контекста извне!

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/api/handlers/registration.go
> +			UUID:     uuid.NewString(),
 Принимается, но мне все же кажется, что это оверхэд, так как таких требований нет.

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/repository/models/balance.go
> +	Value     float64      `json:"value"`
Вообще хранение и совершение операций с деньгами при помощи типов с плавающей точкой могу вести к неявным ошибкам, так как при математических операциях могу быть неявные округления и т.д., так как это бинарные, а не десятичные типы. Я бы рекомендовал использовать либо то, что называется minimal currency unit (т.е. хранить копейки вместо рублей в целочисленном типе и форматировать их соответствующим образом, когда это необходимо) либо использовать тип `decimal`. Так как в Go нет нативного `decimal` типа, можно использовать сторонние библиотеки.

2024-10-02 02:52 UTC, vokinneberg commented on internal/accrual/api/client/client.go
> +}
Рекомендовал бы сгруппировать типы так, чтобы типы и их методы были ближе друг к другу. 
```suggestion
type ResponseAccrual struct {
	Order   string  `json:"order"`
	Status  string  `json:"status"`
	Accrual float64 `json:"accrual"`
}

type AccrualClient struct {
	serviceURL string
	logger     *logger.Logger
}

func NewAccrualClient(serviceURL string, logger *logger.Logger) *AccrualClient {
	instance := &AccrualClient{
		serviceURL: serviceURL,
		logger:     logger,
	}
	return instance
}
```

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/api/routes.go
> +		r.With(
Если честно, то мне кажется такой подход избыточным. По моему мнению, в общем случае middleware стоит использовать для реализации общих технических аспектов, которые напрямую не относятся к бизнес-логике приложения: логирование, сжатие, авторизация, recovery и т.д. То, что, как правило, будет использоваться несколько раз для разных маршрутов приложения. Бизнес-логику всё же стоит поместить на уровень хэндлера или сервиса, если такой слой есть в приложении, и не стоит разделять на отдельные файлы, так как это только добавляет дополнительную когнитивную нагрузку и усложняет понимание того, как же работает приложение, не говоря уже о тестировании.

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/worker/worker.go
> +const workerNum = 3
Стоит вынести в настройки.

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/api/handlers/balance.go
> +		Current:   0,
Кстати говоря, значение по-умолчанию для численных типов будет `0`, так что не всегда обязательно устанавливать его явно.

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/api/handlers/context_test.go
> +func TestAddCommonContext(t *testing.T) {
В этом тесте нужен какой-то ассерт, я полагаю?

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/api/handlers/withdraw.go
> +		res.WriteHeader(http.StatusUnprocessableEntity)
Мне кажется это все же `400 BadRequest`, а не `StatusUnprocessableEntity`.

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/api/handlers/withdraw.go
> +	if existWithdraw != nil && existWithdraw.ID > 0 {
Мне кажется это все же `400 BadRequest`, а не `StatusUnprocessableEntity`.

2024-10-02 02:52 UTC, vokinneberg commented on internal/app/repository/accrual.go
> +		logger.LogSugar.Errorf("При вызове UpdateByOrderNumber(%s, %s, %f) произошла ошибка %s", orderNumber, orderStatus, accrual, err)
Ты логируешь во всех слоях приложения, на самом деле на мой взгляд такое логирование немного избыточно и создает много «шума». В Go существует техника враппинга ошибок, когда к ошибке добавляется контекст и она возвращается вверх по стеку вызовов, где логируется в некой единой точке обработки. Рекомендую попробовать использовать такую технику.

2024-10-02 17:06 UTC, northmule commented on config/config_test.go
> +			assert.Equal(t, test.expected.LogLevel, cfg.LogLevel)
В данном случае не соглашусь, так как это разные типы структур

2024-10-03 09:24 UTC, northmule commented on internal/app/repository/models/balance.go
> +	Value     float64      `json:"value"`
Переделал на decimal, думал что в Go нет проблемы с float как в других языках, спасибо за наводку. Хотел везде переделать, но есть места где в ответах остался float, там где автотесты ждут только float

2024-10-03 18:19 UTC, northmule commented on cmd/gophermart/main.go
> +		<-ctx.Done()
Здесь второй вариант, который работает следующим образом:
1. Создаётся контекст приложения черезы вызов signal.NotifyContext который ожидает сигналы
2. Создаётся горутина в которой будет выполнена остановка сервера когда такой сигнал будет получен (выполнится блок кода следующий за <-ctx.Done())
3. Вне рамок горутины запускается сервер

2024-10-03 18:22 UTC, northmule commented
Вопрос по бинарнику goose.
Если есть необходимость создавать миграции и их применять в локальном окружении, например через 
./cmd/goose/goose -dir db/migrations create jobs_table sql или ./cmd/goose/goose  -dir db/migrations postgres "postgres://postgres:123@localhost:5456/gofermart?sslmode=disable" up
В этом случае не оправданно хранение бинарника в папке проекта?

2024-10-03 22:31 UTC, vokinneberg commented
@northmule Я думаю, это не оправдано, исходя из сценариев использования:

- Когда мы выполняем команду на своей машине, предполагается, что у нас либо установлен бинарник, либо мы можем его установить.
- Когда выполняем в GitHub, такие вещи, как правило, скачиваются и устанавливаются в момент выполнения посредством команд GitHub Actions.
- Если используем Docker, то также эти компоненты скачиваются и устанавливаются в момент выполнения.

2024-10-03 22:41 UTC, vokinneberg approved these changes
Поздравляю, ты отлично справился с первым выпускным проектом! 🎉 Ты реализовал большое количество предложений, которые я сделал на предыдущем ревью, здорово! 👍 Твоё приложение стало лучше, оно функционально и проходит все функциональные тесты. 🚀 

**Сильные стороны твоего PR:**

- Ты добавил использование `decimal` для хранения денег 👍
- Ты добавил индексы на поля по которым происходит поиск 👍

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

- На будущее рекомендую все же реализовывать больше тестов, так как по опыту это помогает избежать большого количества багов - падает как правило код не покрытый тестами, а так же позволяет улучшить дизайн приложения.

2024-10-03 22:41 UTC, vokinneberg commented on config/config.go
> +	WorkerNum int `env:"WORKER_NUM"`
👍

2024-10-07 05:52 UTC, merged